insert into PERSONS (id, name) values (1, 'Emelita');
insert into PERSONS (id, name) values (2, 'Clyde');
insert into PERSONS (id, name) values (3, 'Melloney');
insert into PERSONS (id, name) values (4, 'Lorens');
insert into PERSONS (id, name) values (5, 'Corabel');
insert into PERSONS (id, name) values (6, 'Sally');
insert into PERSONS (id, name) values (7, 'Darin');
insert into PERSONS (id, name) values (8, 'Helenelizabeth');
insert into PERSONS (id, name) values (9, 'Mathias');
insert into PERSONS (id, name) values (10, 'Sonya');

insert into CARS (id, name) values (1, 'A6');
insert into CARS (id, name) values (2, 'Charger');
insert into CARS (id, name) values (3, 'Santa Fe');
insert into CARS (id, name) values (4, 'Rio');
insert into CARS (id, name) values (5, 'Yukon');
insert into CARS (id, name) values (6, 'GLI');
insert into CARS (id, name) values (7, 'TSX');
insert into CARS (id, name) values (8, 'Countach');
insert into CARS (id, name) values (9, 'Crown Victoria');
insert into CARS (id, name) values (10, 'Aveo');